# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/_images` folder and
# use grunt task `build` to synchronize assets

# Image directory (default: images)
image_dir: assets/images

# Sidebar Configuration
#    You can add groups of links and links much as you want
#    You just have to respect the indentation : `groups of links` -> `link` -> `title, link, icon`
#    Example :
#    -------------
#       sidebar:                   # DON'T modify this variable name
#            menu:                 # Name of your groups of links (changeable)
#                home:             # Name of your link (changeable)
#                   title: Home    # Title of your link displayed
#                   url: /         # URL of the link. If the URL is internal, domain name is not necessary
#                   icon: home     # Name of the font awesome icon class without the `fa-`
#                                  # Go to http://fontawesome.io/icons/ to find class name of icon
sidebar:
    menu:
        home:
            title: Home
            url: /
            icon: home
        faith:
            title: Faith
            url: /faith
            icon: flame
        categories:
            title: Categories
            url: /all-categories
            icon: bookmark
        tags:
            title: Tags
            url: /all-tags
            icon: tags
        archives:
            title: Archives
            url: /archives
            icon: archive
    author_links:
        github:
            title: GitHub
            url: https://github.com/vanwagonet
            icon: github
        stack_overflow:
            title: Stack Overflow
            url: http://stackoverflow.com/users/1701761/andy-vanwagoner
            icon: stack-overflow
        # twitter:
        #     title: Twitter
        #     url: https://twitter.com/thetalecrafter
        #     icon: twitter
        # facebook:
        #     title: Facebook
        #     url: https://www.facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: Google +
        #     url: https://plus.google.com/
        #     icon: google-plus
        linked_in:
            title: LinkedIn
            url: https://www.linkedin.com/in/andrewvanwagoner
            icon: linkedin
        # keybase:
        #     title: Keybase
        #     url: https://keybase.io/thetalecrafter
        #     icon: key
        # coinbase:
        #     title: Coinbase
        #     url: https://www.coinbase.com/thetalecrafter
        #     icon: btc
        # mail:
        #     title: Mail
        #     url: mailto://
        #     icon: envelope-o
    rss:
        rss:
            title: Feed
            url: /atom.xml
            icon: rss

# Author
author:
    email: andy@vanwago.net
    bio: Just trying to make the world a little better
    job: Software Engineer
    location: Utah
    picture: andy.jpg
                # Your profile picture located in folder `source/_images/` (development)
                # or in `source/assets/images/` (production)
                # Overwritten by your gravatar image if `gravatar_image` is enabled

# Customization
gravatar_image: 0                      # Enable gravatar image. Using `author.email` value. (disable: 0, enable: 1). Overwrite `author.picture` everywhere in the blog
thumbnail_image: 1                     # Display thumbnail image of each post on index pages (disable: 0, enable: 1)
read_more_message: Continue reading    # Message displayed after the <!-- more --> tag
go_to_message: Go to the website       # Message displayed after the <!-- more --> tag or after 300 characters for post with link layout
favicon: favicon.ico                   # Your favicon located in folder `source/_images/` (development) or in `source/assets/images/` (production)
image_gallery: 1                       # Display an image gallery at the end of a post which have photos variables
